User.destroy_all
u1 = User.create :email => 'karen@ga.co', :password => 'chicken', :admin => true
u2 = User.create :email => 'lisa@ga.co', :password => 'chicken'
puts "#{ User.count } users created"

Recipe.destroy_all
r1 = Recipe.create :title => 'Chinese Tomato and Egg', :description => 'The tangy tomatoes, mixed with rich scrambled eggs, a hint of sugar, and flavorful sesame oil and Shaoxing wine all come together to create a very satisfying (and vegetarian!) dish that tastes lovely on a bed of rice.', :servings => '2', :preptime => '10 mins', :cooktime => '10 mins', :ingredients => '4 eggs,1 scallion, 2 small to medium tomatoes, 3/4 tsp salt, 1/4 tsp white pepper, 1/2 tsp sesame oil, 1 tsp shaoxing wine, 3 tbsp vegetable oil, 2 tsp sugar, 1/4 - 1/2 cup water', :instructions => 'Start by cutting tomatoes into small wedges and finely chop the scallion._Crack 4 eggs into a bowl and season with 1⁄4 teaspoon salt, 1/4 teaspoon white pepper, 1/2 teaspoon sesame oil, and 1 teaspoon Shaoxing wine. Beat eggs for a minute._Preheat the wok over medium heat until it just starts to smoke. Then add 2 tablespoons of oil and immediately add the eggs. Scramble the eggs and remove from the wok immediately. Set aside._Add 1 more tablespoon oil to the wok, turn up the heat to high, and add the tomatoes and scallions. Stir-fry for 1 minute, and then add 2 teaspoons sugar, 1/2 teaspoon salt, and 1/4 cup water (if your stove gets very hot and liquid tends to cook off very quickly in your wok, add a little more water). Add the cooked eggs._Mix everything together, cover the wok, and cook for 1-2 minutes, until the tomatoes are completely softened._Uncover, and continue to stir-fry over high heat until the sauce thickens to your liking. Serve!', :image => 'https://thewoksoflife.com/wp-content/uploads/2019/05/tomato-egg-11.jpg', :video => 'https://www.youtube.com/watch?v=Wn8ox93Qhus'
r2 = Recipe.create :title => 'Canned Tuna Pasta', :description => 'Tuna pasta is such a great dinner to make when you don’t have much in the cupboard. For canned tuna recipe cynics out there – it’s time to take a leap of faith! This is seriously tasty, very economical and super fast – it comes together in 15 minutes flat, from start to finish.', :servings => '2', :preptime => '5 mins', :cooktime => '15 mins', :ingredients => '200g spaghetti, 1bsp salt (for cooking pasta), 285g canned tuna in oil, 2 clove garlic, 1/2 tsp chilli flakes, 2 tsp baby capers, 1 tbsp parsley, 1 tsp lemon zest, 2 tbsp lemon juice, 1/4 tsp salt, 1/4 tsp black pepper', :instructions => 'Cook pasta - Bring 3 litres of water to the boil with the 1 tablespoon of salt. Cook pasta per the packet time minus 1 minute. Just before draining, scoop out ~1 cup pasta cooking water, then drain the pasta._Saute aromatics - In the same pot, heat the reserved oil from the tuna cans over medium heat. Add the garlic, anchovies and chilli flakes. Cook and stir for 1 minute._Toss pasta - Add the pasta, capers and 1/3 cup of reserved pasta water. Toss using 2 spatulas for 2 minutes._Add tuna - Turn off the heat. Add tuna, parsley, lemon zest, juice, salt and pepper. Toss gently to mix through – try to keep some tuna chunks.', :image => 'https://www.recipetineats.com/wp-content/uploads/2023/04/Canned-tuna-pasta_0-copy.jpg', :video => 'https://www.youtube.com/watch?v=yoSQ7cLUyLs'
puts "#{ Recipe.count } recipes created."

Category.destroy_all
c1 = Category.create :name => "Beef", :description => "Beef is a versatile protein that can be prepared in many ways, making it a staple in cuisines worldwide. From succulent steaks to hearty stews, our beef recipes offer a range of flavors and textures to elevate any meal."
c2 = Category.create :name => "Chicken & Poultry", :description => "Chicken and poultry are lean protein sources that can be cooked in a variety of ways, making them a popular ingredient in many cuisines. From tender roasted chicken to spicy grilled kebabs, our collection of chicken and poultry recipes will provide you with endless inspiration to create delicious and healthy meals."
c3 = Category.create :name => "Pork", :description => "Pork is a versatile and flavorful protein that can be cooked in various ways, offering a range of textures and tastes. Whether you're in the mood for juicy pork chops, crispy bacon, or tender pulled pork, our pork recipes are sure to satisfy your cravings and help you create mouth-watering meals."
c4 = Category.create :name => "Lamb", :description => "Lamb is a succulent and richly flavored meat that is enjoyed in many parts of the world. From tender lamb chops to slow-cooked shanks, our lamb recipes offer a range of delicious options for any occasion. Explore our collection and discover new ways to enjoy this versatile protein in your cooking."
c5 = Category.create :name => "Fish & Seafood", :description => "Fish and seafood are a healthy and delicious protein choice that can be prepared in many ways, offering a wide range of flavors and textures. From delicate white fish to robust shellfish, our collection of fish and seafood recipes will inspire you to create mouth-watering dishes that are perfect for any occasion. Dive into our selection and discover new ways to enjoy these nutritious and flavorful ingredients in your cooking."
c6 = Category.create :name => "Eggs", :description => "Eggs are a versatile and nutritious ingredient that can be cooked in various ways, making them a staple in many kitchens around the world. From classic scrambled eggs to fluffy omelets, our egg recipes offer a range of tasty options for any meal of the day. Whether you're looking for a quick breakfast or a satisfying brunch, our collection will provide you with plenty of inspiration to create delicious dishes that are sure to impress."
c7 = Category.create :name => "Vegetarian", :description => "Our vegetarian recipes showcase the diverse and flavorful ways in which meat-free dishes can be prepared, from hearty stews to spicy curries. Whether you're a vegetarian or looking to add more plant-based meals to your diet, our collection offers inspiration to create delicious and wholesome dishes."
c8 = Category.create :name => "Tofu", :description => "Tofu is a versatile and protein-rich ingredient that is a staple in many vegetarian and vegan diets. From stir-fries to salads, our tofu recipes offer a range of tasty and creative ways to incorporate this nutritious ingredient into your meals."
c9 = Category.create :name => "Bread & Pizza", :description => "Bread and pizza are staples in many cuisines around the world, and for good reason. Our collection of bread and pizza recipes offers a range of options from classic sourdough loaves to homemade pizza crusts, providing endless inspiration to create delicious and comforting baked goods."
c10 = Category.create :name => "Noodles & Pasta", :description => "Noodles and pasta are a versatile and comforting ingredient that can be prepared in countless ways, making them a favorite in many cuisines around the world. From creamy carbonara to spicy arrabbiata, our noodle and pasta recipes offer a range of delicious and satisfying meal options that are perfect for any occasion."
c11 = Category.create :name => "Rice", :description => "Rice is a staple food in many cultures and cuisines, offering a versatile and affordable ingredient that can be prepared in countless ways. From fragrant pilafs to creamy risottos, our collection of rice recipes provides a range of tasty and satisfying meal options that are easy to make and perfect for any occasion."
c12 = Category.create :name => "Soups & Stocks", :description => "Soups and stocks are the foundation of many delicious meals, providing rich and flavorful bases that are perfect for adding depth and complexity to dishes. From hearty stews to creamy bisques, our soup and stock recipes offer a range of tasty and comforting options that are perfect for any occasion."
c13 = Category.create :name => "Dessert", :description => "Dessert is the perfect way to end any meal on a sweet note, offering a range of indulgent and delicious treats that can satisfy any sweet tooth. From classic chocolate cakes to fruity tarts, our dessert recipes provide a range of options that are easy to make and sure to impress."
puts "#{ Category.count } categories created."

puts "Categories and Recipes"
c6.recipes << r1 << r2
c5.recipes << r2
puts "Categories and Recipes associated"